name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build
        run: npm run build

      - name: Create 404.html
        run: |
          cp dist/index.html dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
          commit_message: "Deploy from main branch"
          full_commit_message: "Deploy from main branch [skip ci]"
          
      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          
      - name: Check deployment
        run: |
          echo "Checking deployment..."
          for i in {1..5}; do
            if curl -s -o /dev/null -w "%{http_code}" https://pomidorkaeg.github.io/fdfdsdfds/ | grep -q "200"; then
              echo "Deployment successful!"
              exit 0
            fi
            echo "Attempt $i: Deployment not ready yet..."
            sleep 15
          done
          echo "Deployment check failed"
          exit 1 